###############################
# Makefile for Include Files
###############################
all : 
# done call make here	
	cd ..; make 

clean:
	rm -f *~

distclean: clean
	rm -f config.h locations.h snprintf.h dh.h

devclean: distclean
